include(CMakeFindDependencyMacro)
find_package(Boost 1.68 COMPONENTS system date_time thread chrono random REQUIRED)
include(${CMAKE_CURRENT_LIST_DIR}/FindAzmqLibzmq.cmake)
set(CMAKE_THREAD_PREFER_PTHREAD TRUE)
find_package(Threads REQUIRED)
include("${CMAKE_CURRENT_LIST_DIR}/azmqTargets.cmake")